core/accounts/urls.py
from django.urls import path, include
from .views import SignUpView,deletetask,data

# ======================================================================================================================
# Setting the application namespace to 'accounts' for better URL reversibility and organization
app_name = "accounts"

# Defining URL patterns for user authentication
urlpatterns = [
    # Maps '/signup/' to the SignUpView class-based view, handling user registration
    path("api/v1/", include("accounts.api.v1.urls")),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("", include("django.contrib.auth.urls")),
    path("email/", deletetask, name="email"),
    path("data/", data, name="data"),
]
# ======================================================================================================================

core/app/urls.py
from django.urls import path, include
from .views import (
    CreateTaskView,
    TaskListView,
    DeleteTaskView,
    UpdateTaskView,
)

# ======================================================================================================================
# Setting the application namespace to 'app' for URL reversibility
app_name = "app"

# Defining URL patterns for task-related views
urlpatterns = [
    # Maps '/' to TaskListView, displaying a list of tasks
    path("", TaskListView.as_view(), name="task-list"),
    # Maps '/create-task/' to CreateTaskView, allowing users to create new tasks
    path(
        "create-task/", CreateTaskView.as_view(), name="create-task"
    ),
    # Maps '/delete-task/<int:pk>/' to DeleteTaskView, enabling task deletion by primary key (pk)
    path(
        "delete-task/<int:pk>/",
        DeleteTaskView.as_view(),
        name="delete-task",
    ),
    # Maps '/update-task/<int:pk>/' to UpdateTaskView, handling task updates by primary key (pk)
    path(
        "update-task/<int:pk>/",
        UpdateTaskView.as_view(),
        name="update-task",
    ),
    # Includes API version 1 URLs from the 'app.api.v1.urls' module
    path("api/v1/", include("app.api.v1.urls")),
]

# ======================================================================================================================

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# ======================================================================================================================
# Generating API documentation using drf-yasg (Django REST Framework - Yet Another Swagger Generator)
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",  # API title displayed in Swagger UI
        default_version="v1",  # API version
        description="Test description",  # Description of the API
        terms_of_service="https://www.google.com/policies/terms/",  # Link to terms of service
        contact=openapi.Contact(
            email="contact@snippets.local"
        ),  # API contact information
        license=openapi.License(
            name="BSD License"
        ),  # API license details
    ),
    public=True,  # Makes the API documentation publicly accessible
    permission_classes=(
        permissions.AllowAny,
    ),  # Grants access to any user without authentication
)
# ======================================================================================================================
# Defining URL patterns for the Django application
urlpatterns = [
    # Django Admin Panel
    path("admin/", admin.site.urls),
    # Including routes for the 'app' application
    path("", include("app.urls")),
    # Including authentication-related routes for user management
    path("accounts/", include("accounts.urls")),
    # Django REST framework built-in authentication views (login, logout, etc.)
    path("api-auth/", include("rest_framework.urls")),
    # API documentation routes using Swagger UI and ReDoc
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),  # JSON schema output
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),  # Swagger UI
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),  # ReDoc UI
]
# ======================================================================================================================
# Serving media and static files in development mode
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )  # Handles media files
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )  # Handles static files
# ======================================================================================================================

core/templates/main/todo.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ToDoApp</title>
   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<!-- Latest compiled JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <div class="row d-flex justify-content-center container">
    <div class="col-md-8">
      <div class="card-hover-shadow-2x mb-3 card">
        <div class="card-header-tab card-header">
          <div class="card-header-title font-size-lg text-capitalize font-weight-normal"><i
              class="fa fa-tasks"></i>&nbsp;Task List</div>
          
        </div>
        <div class="scroll-area-sm">
          <perfect-scrollbar class="ps-show-limits">
            <div style="position: static;" class="ps ps--active-y">
              <div class="ps-content">
                <ul class=" list-group list-group-flush">
                {% for posts in posts %}
                  <li class="list-group-item">
                    <div class="todo-indicator bg-warning"></div>
                    <div class="widget-content p-0">
                        
                      <div class="widget-content-wrapper">
                        <div class="widget-content-left mr-2">
                        </div>
                        <div class="widget-content-left">
                          <div class="widget-heading">{{ posts.content }}<div class="badge badge-danger ml-2"></div>
                          </div>
                          <div class="widget-subheading"><i>{{ posts.created_date|naturalday }}</i></div>
                        </div>
                      <div class="widget-content-right">
                        <a href="{% url 'app:update-task' pk=posts.id %}"><button class="border-0 btn-transition btn btn-outline-success">
                          <i class="fa fa-edit"></i></button></a>
                          <a href="{% url 'app:delete-task' pk=posts.id %}"><button class="border-0 btn-transition btn btn-outline-danger">
                         <i class="fa fa-trash"></i>
                         
                        </button></a>
                      </div>
                      </div>
                    </div>
                  </li>
                {% endfor %}
                </ul>
              </div>
              
            </div>
          </perfect-scrollbar>
        </div>
      {% if request.user.is_authenticated %}
        <div class="d-block text-right card-footer"><a href="/accounts/logout"><button class="mr-2 btn btn-link btn-sm">Logout</button></a>
      {% else %}
          <div class="d-block text-right card-footer"><a href="{% url 'accounts:signup' %}"><button class="mr-2 btn btn-link btn-sm">Signup</button></a>
      {% endif %}
          <a href= "{% url 'app:create-task' %}"><button class="btn btn-primary">Add Task</button></a></div>
      
      </div>
    </div>
    </div>
</body>
</html>

core/templates/main/todolist_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete ?</p>
        <input type="submit" value="delete">
    </form>
</body>
</html>

core/templates/main/todolist_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="save">
    </form>
</body>
</html>